compatibility_date = "2021-11-12"

name = "adjective-animal"
main = "src/index.ts"
workers_dev = true

[vars]
DISCORD_NACL_PUBLIC_KEY = "6287914aeafeeb18a0363471ada96e23e9ef53843657aa9346c98d98939371e3"
DISCORD_APPLICATION_ID = "536984653483999232"

[[rules]]
type = "ESModule"
globs = [ "**/*.ts" ]
